{
 "title": "x-ui",
 "description": "x-ui-exporter dashboard",
 "time": { "from": "2023-08-21T07:58:32.285Z", "to": "2023-08-22T04:32:59.940Z" },
 "panels": [
  {
   "title": "x-ui流量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "x_ui_all_flow_bytes", "legendFormat": "总流量" },
    { "expr": "x_ui_all_up_flow_bytes", "legendFormat": "总上传流量" },
    { "expr": "x_ui_all_down_flow_bytes", "legendFormat": "总下载流量" }
   ]
  },
  {
   "title": "用户总流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "x_ui_user_all_flow_bytes", "legendFormat": "{{name}}-{{protocol}}总流量" }
   ]
  },
  {
   "title": "用户下载流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "x_ui_user_down_flow_bytes", "legendFormat": "{{name}}-{{protocol}}下载流量" }
   ]
  },
  {
   "title": "用户上传流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "x_ui_user_up_flow_bytes", "legendFormat": "{{name}}-{{protocol}}上传流量" }
   ]
  }
 ]
}